files:
  - source: /**/content/Language.properties
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    languages_mapping:
      two_letters_code:
        zh-CN: locale_with_underscore
        zh-TW: locale_with_underscore
        hi: locale_with_underscore
        sr: locale_with_underscore
        sr-CS: locale_with_underscore
        pt-PT: locale_with_underscore
        pt-BR: locale_with_underscore
